//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1pract.Pages
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peredacha_material_proithvodstvu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Peredacha_material_proithvodstvu()
        {
            this.Material = new HashSet<Material>();
        }
    
        public Nullable<System.DateTime> date_peredache { get; set; }
        public int C_dokymenta { get; set; }
        public Nullable<int> kolichestvo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Material { get; set; }
    }
}
