//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1pract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int id_material { get; set; }
        public string material_name { get; set; }
        public string ved_material { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> nomer_doc_postup { get; set; }
        public Nullable<int> nomer_doc_sps { get; set; }
        public Nullable<int> nomer_doc_per { get; set; }
        public string Photo { get; set; }
    
        public virtual Peredacha_material_proithvodstvu Peredacha_material_proithvodstvu { get; set; }
        public virtual Postuplenie Postuplenie { get; set; }
        public virtual Spisanie_materialov Spisanie_materialov { get; set; }
    }
}
