//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1pract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spisanie_materialov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spisanie_materialov()
        {
            this.Material = new HashSet<Material>();
        }
    
        public Nullable<System.DateTime> date_spisanie { get; set; }
        public int C__document { get; set; }
        public Nullable<int> kolvo { get; set; }
        public Nullable<int> summa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Material { get; set; }
    }
}
